/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Slava Z. (https://sketchfab.com/slava)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pony-cartoon-885d9f60b3a9429bb4077cfac5653cf9
Title: Pony Cartoon
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

function GltfComponent(props) {
  const { nodes, materials } = useGLTF("./models/pony_cartoon/scene.gltf");
  const ref = useRef();
  useFrame((state, delta) => {
    ref.current.rotation.y += delta * 0.3;
  });
  return (
    <group ref={ref} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.004}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Body_SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Ground_SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Interior_SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Windows_SG}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/pony_cartoon/scene.gltf");

export default GltfComponent;
